#!/usr/bin/env bash

# Function to print domain and subdomain information
print_domain_subdomain () {
    local result=$(dig "$1" +short)
    local subdomain=$2
    local ip_address=$(echo "$result" | head -n1)

    if [ -z "$ip_address" ]; then
        echo "No record found for $subdomain"
    else
        local record_type=$(dig "$1" | awk '/ANSWER SECTION/ {getline; print $4}')
        echo "The subdomain $subdomain is a $record_type record and points to $ip_address"
    fi
}

# Check the number of arguments
if [ "$#" -eq 2 ]; then
    print_domain_subdomain "$2.$1" "$2"
else
    print_domain_subdomain "www.$1" "www"
    print_domain_subdomain "lb-01.$1" "lb-01"
    print_domain_subdomain "web-01.$1" "web-01"
    print_domain_subdomain "web-02.$1" "web-02"
fi
