#!/usr/bin/env bash
# configures a new HAproxy as a load balancer

# Install HAproxy on a server
apt-get -y update
apt-get -y install haproxy=1.6.\*

# Configure haproxy configuration file to distribute requests using a roundrobin algorithm
echo '
frontend haproxy_balancer
        bind 0:80
        default_backend web_servers

backend web_servers
        balance roundrobin
        server 331415-web-01 52.86.215.33
        server 331415-web-02 18.209.152.78
' >> /etc/haproxy/haproxy.cfg

# Restart HAproxy service
service haproxy restart
